# Generated by Django 4.2.27 on 2026-01-17 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, help_text='Subject area: Math, Science, English, etc.', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this conversation is still active')),
                ('title', models.CharField(blank=True, help_text='Auto-generated title from first question', max_length=200)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Setting key name', max_length=50, unique=True)),
                ('value', models.TextField(help_text='Setting value (stored as string, parsed as needed)')),
                ('description', models.CharField(blank=True, help_text='Human-readable description of this setting', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField(help_text='The message content')),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice')], default='text', help_text='How the message was input (text or voice)', max_length=10)),
                ('audio_input_path', models.CharField(blank=True, help_text='Path to original audio input file (for voice messages)', max_length=255)),
                ('audio_output_path', models.CharField(blank=True, help_text='Path to TTS audio output file', max_length=255)),
                ('tts_generated', models.BooleanField(default=False, help_text='Whether TTS audio has been generated for this message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
